# Generated by Django 4.2.6 on 2024-05-26 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='cat',
            field=models.CharField(choices=[('Похудение', 'похудение'), ('Спортивное питание', 'спортпит'), ('Веганы и Вегетарианцы', 'веган'), ('Полезно для здоровья', 'здоровье'), ('Анти-Эйджинг', 'анти-Эйджинг'), ('Семейное Питание', 'семья'), ('Питание при Медицинских Состояниях', 'мед')], default='здоровье', max_length=40),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.foodpost')),
            ],
        ),
        migrations.AddField(
            model_name='foodpost',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', through='posts.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
