# Generated by Django 4.2.6 on 2024-05-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_comment_bookmark_foodpost_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefers_organic', models.BooleanField(default=True)),
                ('prefers_low_fat', models.BooleanField(default=True)),
                ('prefers_sugar_free', models.BooleanField(default=True)),
                ('prefers_high_protein', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulnessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.foodpost')),
            ],
        ),
    ]
