# Generated by Django 5.0.4 on 2024-05-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_userpreferences_usefulnesshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='sugar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
