services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    command: >
     sh -c "
     python manage.py wait_for_db &&
     python manage.py makemigrations &&
     python manage.py migrate &&
     python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis

  celery:
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    command: >
      sh -c "celery -A payments beat --loglevel=info &&
             celery -A payments worker --loglevel=info -P eventlet" # Change eventlet to gevent for lighter worker pool
    volumes:
      - ./backend:/app/backend
    depends_on:
     
      - redis
