# Generated by Django 4.2.6 on 2024-05-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='post_images/thug.jpg', upload_to='avatars'),
        ),
    ]
