# Generated by Django 5.0.4 on 2024-05-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_method',
        ),
    ]
